<?php
class Country
{
    private static $countries = [
    "AF" => array("en" => "Afghanistan", "it" => "Afghanistan"),
    "AL" => array("en" => "Albania", "it" => "Albania"),
    "DZ" => array("en" => "Algeria", "it" => "Algeria"),
    "AD" => array("en" => "Andorra", "it" => "Andorra"),
    "AO" => array("en" => "Angola", "it" => "Angola"),
    "AI" => array("en" => "Anguilla", "it" => "Anguilla"),
    "AQ" => array("en" => "Antarctica", "it" => "Antartide"),
    "AG" => array("en" => "Antigua And Barbuda", "it" => "Antigua e Barbuda"),
    "AN" => array("en" => "Netherlands Antilles", "it" => "Antille Olandesi"),
    "SA" => array("en" => "Saudi Arabia", "it" => "Arabia Saudita"),
    "AR" => array("en" => "Argentina", "it" => "Argentina"),
    "AM" => array("en" => "Armenia", "it" => "Armenia"),
    "AW" => array("en" => "Aruba", "it" => "Aruba"),
    "AU" => array("en" => "Australia", "it" => "Australia"),
    "AT" => array("en" => "Austria", "it" => "Austria"),
    "AZ" => array("en" => "Azerbaijan", "it" => "Azerbaigian"),
    "BS" => array("en" => "Bahamas", "it" => "Bahamas"),
    "BH" => array("en" => "Bahrain", "it" => "Bahrein"),
    "BD" => array("en" => "Bangladesh", "it" => "Bangladesh"),
    "BB" => array("en" => "Barbados", "it" => "Barbados"),
    "BE" => array("en" => "Belgium", "it" => "Belgio"),
    "BZ" => array("en" => "Belize", "it" => "Belize"),
    "BJ" => array("en" => "Benin", "it" => "Benin"),
    "BM" => array("en" => "Bermuda", "it" => "Bermuda"),
    "BT" => array("en" => "Bhutan", "it" => "Bhutan"),
    "BY" => array("en" => "Belarus", "it" => "Bielorussia"),
    "BO" => array("en" => "Bolivia", "it" => "Bolivia"),
    "BA" => array("en" => "Bosnia And Herzegovina", "it" => "Bosnia ed Erzegovina"),
    "BW" => array("en" => "Botswana", "it" => "Botswana"),
    "BR" => array("en" => "Brazil", "it" => "Brasile"),
    "BN" => array("en" => "Brunei Darussalam", "it" => "Brunei"),
    "BG" => array("en" => "Bulgaria", "it" => "Bulgaria"),
    "BF" => array("en" => "Burkina Faso", "it" => "Burkina Faso"),
    "BI" => array("en" => "Burundi", "it" => "Burundi"),
    "KH" => array("en" => "Cambodia", "it" => "Cambogia"),
    "CM" => array("en" => "Cameroon", "it" => "Camerun"),
    "CA" => array("en" => "Canada", "it" => "Canada"),
    "CV" => array("en" => "Cape Verde", "it" => "Capo Verde"),
    "TD" => array("en" => "Chad", "it" => "Ciad"),
    "CL" => array("en" => "Chile", "it" => "Cile"),
    "CN" => array("en" => "China", "it" => "Cina"),
    "CY" => array("en" => "Cyprus", "it" => "Cipro"),
    "CO" => array("en" => "Colombia", "it" => "Colombia"),
    "KM" => array("en" => "Comoros", "it" => "Comore"),
    "CG" => array("en" => "Congo", "it" => "Congo"),
    "KR" => array("en" => "Korea", "it" => "Corea del Sud"),
    "CI" => array("en" => "Cote D'Ivoire", "it" => "Costa d'Avorio"),
    "CR" => array("en" => "Costa Rica", "it" => "Costa Rica"),
    "HR" => array("en" => "Croatia", "it" => "Croazia"),
    "CU" => array("en" => "Cuba", "it" => "Cuba"),
    "DK" => array("en" => "Denmark", "it" => "Danimarca"),
    "DM" => array("en" => "Dominica", "it" => "Dominica"),
    "EC" => array("en" => "Ecuador", "it" => "Ecuador"),
    "EG" => array("en" => "Egypt", "it" => "Egitto"),
    "SV" => array("en" => "El Salvador", "it" => "El Salvador"),
    "AE" => array("en" => "United Arab Emirates", "it" => "Emirati Arabi Uniti"),
    "ER" => array("en" => "Eritrea", "it" => "Eritrea"),
    "EE" => array("en" => "Estonia", "it" => "Estonia"),
    "ET" => array("en" => "Ethiopia", "it" => "Etiopia"),
    "RU" => array("en" => "Russian Federation", "it" => "Federazione Russa"),
    "FJ" => array("en" => "Fiji", "it" => "Figi"),
    "PH" => array("en" => "Philippines", "it" => "Filippine"),
    "FI" => array("en" => "Finland", "it" => "Finlandia"),
    "FR" => array("en" => "France", "it" => "Francia"),
    "GA" => array("en" => "Gabon", "it" => "Gabon"),
    "GM" => array("en" => "Gambia", "it" => "Gambia"),
    "GE" => array("en" => "Georgia", "it" => "Georgia"),
    "GS" => array("en" => "South Georgia And Sandwich Isl.", "it" => "Georgia del Sud e Isole Sandwich Australi"),
    "DE" => array("en" => "Germany", "it" => "Germania"),
    "GH" => array("en" => "Ghana", "it" => "Ghana"),
    "JM" => array("en" => "Jamaica", "it" => "Giamaica"),
    "JP" => array("en" => "Japan", "it" => "Giappone"),
    "GI" => array("en" => "Gibraltar", "it" => "Gibilterra"),
    "DJ" => array("en" => "Djibouti", "it" => "Gibuti"),
    "JO" => array("en" => "Jordan", "it" => "Giordania"),
    "GR" => array("en" => "Greece", "it" => "Grecia"),
    "GD" => array("en" => "Grenada", "it" => "Grenada"),
    "GL" => array("en" => "Greenland", "it" => "Groenlandia"),
    "GP" => array("en" => "Guadeloupe", "it" => "Guadalupa"),
    "GU" => array("en" => "Guam", "it" => "Guam"),
    "GT" => array("en" => "Guatemala", "it" => "Guatemala"),
    "GG" => array("en" => "Guernsey", "it" => "Guernsey"),
    "GN" => array("en" => "Guinea", "it" => "Guinea"),
    "GQ" => array("en" => "Equatorial Guinea", "it" => "Guinea Equatoriale"),
    "GW" => array("en" => "Guinea-Bissau", "it" => "Guinea-Bissau"),
    "GY" => array("en" => "Guyana", "it" => "Guyana"),
    "GF" => array("en" => "French Guiana", "it" => "Guyana Francese"),
    "HT" => array("en" => "Haiti", "it" => "Haiti"),
    "HN" => array("en" => "Honduras", "it" => "Honduras"),
    "HK" => array("en" => "Hong Kong", "it" => "Hong Kong"),
    "IN" => array("en" => "India", "it" => "India"),
    "ID" => array("en" => "Indonesia", "it" => "Indonesia"),
    "IR" => array("en" => "Iran, Islamic Republic Of", "it" => "Iran"),
    "IQ" => array("en" => "Iraq", "it" => "Iraq"),
    "IE" => array("en" => "Ireland", "it" => "Irlanda"),
    "IS" => array("en" => "Iceland", "it" => "Islanda"),
    "BV" => array("en" => "Bouvet Island", "it" => "Isola Bouvet"),
    "IM" => array("en" => "Isle Of Man", "it" => "Isola di Man"),
    "CX" => array("en" => "Christmas Island", "it" => "Isola di Natale"),
    "NF" => array("en" => "Norfolk Island", "it" => "Isola Norfolk"),
    "AX" => array("en" => "Aland Islands", "it" => "Isole Åland"),
    "KY" => array("en" => "Cayman Islands", "it" => "Isole Cayman"),
    "CC" => array("en" => "Cocos (Keeling) Islands", "it" => "Isole Cocos (Keeling)"),
    "CK" => array("en" => "Cook Islands", "it" => "Isole Cook"),
    "FK" => array("en" => "Falkland Islands (Malvinas)", "it" => "Isole Falkland (Malvine)"),
    "FO" => array("en" => "Faroe Islands", "it" => "Isole Faroe"),
    "HM" => array("en" => "Heard Island & Mcdonald Islands", "it" => "Isole Heard e McDonald"),
    "MP" => array("en" => "Northern Mariana Islands", "it" => "Isole Marianne Settentrionali"),
    "MH" => array("en" => "Marshall Islands", "it" => "Isole Marshall"),
    "UM" => array("en" => "United States Outlying Islands", "it" => "Isole Minori Esterne degli Stati Uniti"),
    "SB" => array("en" => "Solomon Islands", "it" => "Isole Salomone"),
    "TC" => array("en" => "Turks And Caicos Islands", "it" => "Isole Turks e Caicos"),
    "VI" => array("en" => "Virgin Islands, U.S.", "it" => "Isole Vergini Americane"),
    "VG" => array("en" => "Virgin Islands, British", "it" => "Isole Vergini Britanniche"),
    "IL" => array("en" => "Israel", "it" => "Israele"),
    "IT" => array("en" => "Italy", "it" => "Italia"),
    "JE" => array("en" => "Jersey", "it" => "Jersey"),
    "KZ" => array("en" => "Kazakhstan", "it" => "Kazakistan"),
    "KE" => array("en" => "Kenya", "it" => "Kenya"),
    "KG" => array("en" => "Kyrgyzstan", "it" => "Kirghizistan"),
    "KI" => array("en" => "Kiribati", "it" => "Kiribati"),
    "KW" => array("en" => "Kuwait", "it" => "Kuwait"),
    "LA" => array("en" => "Lao People's Democratic Republic", "it" => "Laos"),
    "LS" => array("en" => "Lesotho", "it" => "Lesotho"),
    "LV" => array("en" => "Latvia", "it" => "Lettonia"),
    "LB" => array("en" => "Lebanon", "it" => "Libano"),
    "LR" => array("en" => "Liberia", "it" => "Liberia"),
    "LY" => array("en" => "Libyan Arab Jamahiriya", "it" => "Libia"),
    "LI" => array("en" => "Liechtenstein", "it" => "Liechtenstein"),
    "LT" => array("en" => "Lithuania", "it" => "Lituania"),
    "LU" => array("en" => "Luxembourg", "it" => "Lussemburgo"),
    "MO" => array("en" => "Macao", "it" => "Macao"),
    "MK" => array("en" => "Macedonia", "it" => "Macedonia del Nord"),
    "MG" => array("en" => "Madagascar", "it" => "Madagascar"),
    "MW" => array("en" => "Malawi", "it" => "Malawi"),
    "MV" => array("en" => "Maldives", "it" => "Maldive"),
    "MY" => array("en" => "Malaysia", "it" => "Malesia"),
    "ML" => array("en" => "Mali", "it" => "Mali"),
    "MT" => array("en" => "Malta", "it" => "Malta"),
    "MA" => array("en" => "Morocco", "it" => "Marocco"),
    "MQ" => array("en" => "Martinique", "it" => "Martinica"),
    "MR" => array("en" => "Mauritania", "it" => "Mauritania"),
    "MU" => array("en" => "Mauritius", "it" => "Mauritius"),
    "YT" => array("en" => "Mayotte", "it" => "Mayotte"),
    "MX" => array("en" => "Mexico", "it" => "Messico"),
    "FM" => array("en" => "Micronesia, Federated States Of", "it" => "Micronesia"),
    "MD" => array("en" => "Moldova", "it" => "Moldavia"),
    "MC" => array("en" => "Monaco", "it" => "Monaco"),
    "MN" => array("en" => "Mongolia", "it" => "Mongolia"),
    "ME" => array("en" => "Montenegro", "it" => "Montenegro"),
    "MS" => array("en" => "Montserrat", "it" => "Montserrat"),
    "MZ" => array("en" => "Mozambique", "it" => "Mozambico"),
    "MM" => array("en" => "Myanmar", "it" => "Myanmar (Birmania)"),
    "NA" => array("en" => "Namibia", "it" => "Namibia"),
    "NR" => array("en" => "Nauru", "it" => "Nauru"),
    "NP" => array("en" => "Nepal", "it" => "Nepal"),
    "NI" => array("en" => "Nicaragua", "it" => "Nicaragua"),
    "NE" => array("en" => "Niger", "it" => "Niger"),
    "NG" => array("en" => "Nigeria", "it" => "Nigeria"),
    "NU" => array("en" => "Niue", "it" => "Niue"),
    "NO" => array("en" => "Norway", "it" => "Norvegia"),
    "NC" => array("en" => "New Caledonia", "it" => "Nuova Caledonia"),
    "NZ" => array("en" => "New Zealand", "it" => "Nuova Zelanda"),
    "OM" => array("en" => "Oman", "it" => "Oman"),
    "NL" => array("en" => "Netherlands", "it" => "Paesi Bassi"),
    "PK" => array("en" => "Pakistan", "it" => "Pakistan"),
    "PW" => array("en" => "Palau", "it" => "Palau"),
    "PA" => array("en" => "Panama", "it" => "Panama"),
    "PG" => array("en" => "Papua New Guinea", "it" => "Papua Nuova Guinea"),
    "PY" => array("en" => "Paraguay", "it" => "Paraguay"),
    "PE" => array("en" => "Peru", "it" => "Perù"),
    "PN" => array("en" => "Pitcairn", "it" => "Pitcairn"),
    "PF" => array("en" => "French Polynesia", "it" => "Polinesia Francese"),
    "PL" => array("en" => "Poland", "it" => "Polonia"),
    "PR" => array("en" => "Puerto Rico", "it" => "Porto Rico"),
    "PT" => array("en" => "Portugal", "it" => "Portogallo"),
    "QA" => array("en" => "Qatar", "it" => "Qatar"),
    "GB" => array("en" => "United Kingdom", "it" => "Regno Unito"),
    "CZ" => array("en" => "Czech Republic", "it" => "Repubblica Ceca"),
    "CF" => array("en" => "Central African Republic", "it" => "Repubblica Centrafricana"),
    "CD" => array("en" => "Congo, Democratic Republic", "it" => "Repubblica Democratica del Congo"),
    "DO" => array("en" => "Dominican Republic", "it" => "Repubblica Dominicana"),
    "RE" => array("en" => "Reunion", "it" => "Riunione"),
    "RO" => array("en" => "Romania", "it" => "Romania"),
    "RW" => array("en" => "Rwanda", "it" => "Ruanda"),
    "EH" => array("en" => "Western Sahara", "it" => "Sahara Occidentale"),
    "KN" => array("en" => "Saint Kitts And Nevis", "it" => "Saint Kitts e Nevis"),
    "PM" => array("en" => "Saint Pierre And Miquelon", "it" => "Saint Pierre e Miquelon"),
    "VC" => array("en" => "Saint Vincent And Grenadines", "it" => "Saint Vincent e Grenadine"),
    "BL" => array("en" => "Saint Barthelemy", "it" => "Saint-Barthélemy"),
    "MF" => array("en" => "Saint Martin", "it" => "Saint-Martin"),
    "WS" => array("en" => "Samoa", "it" => "Samoa"),
    "AS" => array("en" => "American Samoa", "it" => "Samoa Americane"),
    "SM" => array("en" => "San Marino", "it" => "San Marino"),
    "SH" => array("en" => "Saint Helena", "it" => "Sant'Elena"),
    "LC" => array("en" => "Saint Lucia", "it" => "Santa Lucia"),
    "VA" => array("en" => "Holy See (Vatican City State)", "it" => "Santa Sede (Città del Vaticano)"),
    "ST" => array("en" => "Sao Tome And Principe", "it" => "São Tomé e Príncipe"),
    "SN" => array("en" => "Senegal", "it" => "Senegal"),
    "RS" => array("en" => "Serbia", "it" => "Serbia"),
    "SC" => array("en" => "Seychelles", "it" => "Seychelles"),
    "SL" => array("en" => "Sierra Leone", "it" => "Sierra Leone"),
    "SG" => array("en" => "Singapore", "it" => "Singapore"),
    "SY" => array("en" => "Syrian Arab Republic", "it" => "Siria"),
    "SK" => array("en" => "Slovakia", "it" => "Slovacchia"),
    "SI" => array("en" => "Slovenia", "it" => "Slovenia"),
    "SO" => array("en" => "Somalia", "it" => "Somalia"),
    "ES" => array("en" => "Spain", "it" => "Spagna"),
    "LK" => array("en" => "Sri Lanka", "it" => "Sri Lanka"),
    "US" => array("en" => "United States", "it" => "Stati Uniti"),
    "ZA" => array("en" => "South Africa", "it" => "Sudafrica"),
    "SD" => array("en" => "Sudan", "it" => "Sudan"),
    "SR" => array("en" => "Suriname", "it" => "Suriname"),
    "SJ" => array("en" => "Svalbard And Jan Mayen", "it" => "Svalbard e Jan Mayen"),
    "SE" => array("en" => "Sweden", "it" => "Svezia"),
    "CH" => array("en" => "Switzerland", "it" => "Svizzera"),
    "SZ" => array("en" => "Swaziland", "it" => "Swaziland"),
    "TJ" => array("en" => "Tajikistan", "it" => "Tagikistan"),
    "TW" => array("en" => "Taiwan", "it" => "Taiwan"),
    "TZ" => array("en" => "Tanzania", "it" => "Tanzania"),
    "TF" => array("en" => "French Southern Territories", "it" => "Territori Francesi del Sud"),
    "PS" => array("en" => "Palestinian Territory, Occupied", "it" => "Territori Palestinesi"),
    "IO" => array("en" => "British Indian Ocean Territory", "it" => "Territorio Britannico dell'Oceano Indiano"),
    "TH" => array("en" => "Thailand", "it" => "Thailandia"),
    "TL" => array("en" => "Timor-Leste", "it" => "Timor Est"),
    "TG" => array("en" => "Togo", "it" => "Togo"),
    "TK" => array("en" => "Tokelau", "it" => "Tokelau"),
    "TO" => array("en" => "Tonga", "it" => "Tonga"),
    "TT" => array("en" => "Trinidad And Tobago", "it" => "Trinidad e Tobago"),
    "TN" => array("en" => "Tunisia", "it" => "Tunisia"),
    "TR" => array("en" => "Turkey", "it" => "Turchia"),
    "TM" => array("en" => "Turkmenistan", "it" => "Turkmenistan"),
    "TV" => array("en" => "Tuvalu", "it" => "Tuvalu"),
    "UA" => array("en" => "Ukraine", "it" => "Ucraina"),
    "UG" => array("en" => "Uganda", "it" => "Uganda"),
    "HU" => array("en" => "Hungary", "it" => "Ungheria"),
    "UY" => array("en" => "Uruguay", "it" => "Uruguay"),
    "UZ" => array("en" => "Uzbekistan", "it" => "Uzbekistan"),
    "VU" => array("en" => "Vanuatu", "it" => "Vanuatu"),
    "VE" => array("en" => "Venezuela", "it" => "Venezuela"),
    "VN" => array("en" => "Viet Nam", "it" => "Vietnam"),
    "WF" => array("en" => "Wallis And Futuna", "it" => "Wallis e Futuna"),
    "YE" => array("en" => "Yemen", "it" => "Yemen"),
    "ZM" => array("en" => "Zambia", "it" => "Zambia"),
    "ZW" => array("en" => "Zimbabwe", "it" => "Zimbabwe"),
    ];

    public static function iso2name(string $iso, $lang = "it"): string
    {
        if (array_key_exists($iso, self::$countries))
            return self::$countries[$iso][$lang];
        else
            throw new Error("Country with ISO Code $iso does not exist.");
    }

    public static function options(string $selected = '', $lang = "it"): void
    {
        foreach (self::$countries as $key => $val) {
            $label = $val[$lang];
            $sel = $selected == $key ? "selected" : "";
            echo "<option value='$key' $sel>$label</option>";
        }
    }
}