<?php
class Country
{
private static $countries = [
    "AF" => array("en" => "Afghanistan", "it" => "Afghanistan", "de" => "Afghanistan"),
    "AL" => array("en" => "Albania", "it" => "Albania", "de" => "Albanien"),
    "DZ" => array("en" => "Algeria", "it" => "Algeria", "de" => "Algerien"),
    "AD" => array("en" => "Andorra", "it" => "Andorra", "de" => "Andorra"),
    "AO" => array("en" => "Angola", "it" => "Angola", "de" => "Angola"),
    "AI" => array("en" => "Anguilla", "it" => "Anguilla", "de" => "Anguilla"),
    "AQ" => array("en" => "Antarctica", "it" => "Antartide", "de" => "Antarktis"),
    "AG" => array("en" => "Antigua And Barbuda", "it" => "Antigua e Barbuda", "de" => "Antigua und Barbuda"),
    "AN" => array("en" => "Netherlands Antilles", "it" => "Antille Olandesi", "de" => "Niederländische Antillen"),
    "SA" => array("en" => "Saudi Arabia", "it" => "Arabia Saudita", "de" => "Saudi-Arabien"),
    "AR" => array("en" => "Argentina", "it" => "Argentina", "de" => "Argentinien"),
    "AM" => array("en" => "Armenia", "it" => "Armenia", "de" => "Armenien"),
    "AW" => array("en" => "Aruba", "it" => "Aruba", "de" => "Aruba"),
    "AU" => array("en" => "Australia", "it" => "Australia", "de" => "Australien"),
    "AT" => array("en" => "Austria", "it" => "Austria", "de" => "Österreich"),
    "AZ" => array("en" => "Azerbaijan", "it" => "Azerbaigian", "de" => "Aserbaidschan"),
    "BS" => array("en" => "Bahamas", "it" => "Bahamas", "de" => "Bahamas"),
    "BH" => array("en" => "Bahrain", "it" => "Bahrein", "de" => "Bahrain"),
    "BD" => array("en" => "Bangladesh", "it" => "Bangladesh", "de" => "Bangladesch"),
    "BB" => array("en" => "Barbados", "it" => "Barbados", "de" => "Barbados"),
    "BE" => array("en" => "Belgium", "it" => "Belgio", "de" => "Belgien"),
    "BZ" => array("en" => "Belize", "it" => "Belize", "de" => "Belize"),
    "BJ" => array("en" => "Benin", "it" => "Benin", "de" => "Benin"),
    "BM" => array("en" => "Bermuda", "it" => "Bermuda", "de" => "Bermuda"),
    "BT" => array("en" => "Bhutan", "it" => "Bhutan", "de" => "Bhutan"),
    "BY" => array("en" => "Belarus", "it" => "Bielorussia", "de" => "Belarus"),
    "BO" => array("en" => "Bolivia", "it" => "Bolivia", "de" => "Bolivien"),
    "BA" => array("en" => "Bosnia And Herzegovina", "it" => "Bosnia ed Erzegovina", "de" => "Bosnien und Herzegowina"),
    "BW" => array("en" => "Botswana", "it" => "Botswana", "de" => "Botswana"),
    "BR" => array("en" => "Brazil", "it" => "Brasile", "de" => "Brasilien"),
    "BN" => array("en" => "Brunei Darussalam", "it" => "Brunei", "de" => "Brunei"),
    "BG" => array("en" => "Bulgaria", "it" => "Bulgaria", "de" => "Bulgarien"),
    "BF" => array("en" => "Burkina Faso", "it" => "Burkina Faso", "de" => "Burkina Faso"),
    "BI" => array("en" => "Burundi", "it" => "Burundi", "de" => "Burundi"),
    "KH" => array("en" => "Cambodia", "it" => "Cambogia", "de" => "Kambodscha"),
    "CM" => array("en" => "Cameroon", "it" => "Camerun", "de" => "Kamerun"),
    "CA" => array("en" => "Canada", "it" => "Canada", "de" => "Kanada"),
    "CV" => array("en" => "Cape Verde", "it" => "Capo Verde", "de" => "Kap Verde"),
    "TD" => array("en" => "Chad", "it" => "Ciad", "de" => "Tschad"),
    "CL" => array("en" => "Chile", "it" => "Cile", "de" => "Chile"),
    "CN" => array("en" => "China", "it" => "Cina", "de" => "China"),
    "CY" => array("en" => "Cyprus", "it" => "Cipro", "de" => "Zypern"),
    "CO" => array("en" => "Colombia", "it" => "Colombia", "de" => "Kolumbien"),
    "KM" => array("en" => "Comoros", "it" => "Comore", "de" => "Komoren"),
    "CG" => array("en" => "Congo", "it" => "Congo", "de" => "Kongo"),
    "KR" => array("en" => "Korea", "it" => "Corea del Sud", "de" => "Südkorea"),
    "CI" => array("en" => "Cote D'Ivoire", "it" => "Costa d'Avorio", "de" => "Elfenbeinküste"),
    "CR" => array("en" => "Costa Rica", "it" => "Costa Rica", "de" => "Costa Rica"),
    "HR" => array("en" => "Croatia", "it" => "Croazia", "de" => "Kroatien"),
    "CU" => array("en" => "Cuba", "it" => "Cuba", "de" => "Kuba"),
    "DK" => array("en" => "Denmark", "it" => "Danimarca", "de" => "Dänemark"),
    "DM" => array("en" => "Dominica", "it" => "Dominica", "de" => "Dominica"),
    "EC" => array("en" => "Ecuador", "it" => "Ecuador", "de" => "Ecuador"),
    "EG" => array("en" => "Egypt", "it" => "Egitto", "de" => "Ägypten"),
    "SV" => array("en" => "El Salvador", "it" => "El Salvador", "de" => "El Salvador"),
    "AE" => array("en" => "United Arab Emirates", "it" => "Emirati Arabi Uniti", "de" => "Vereinigte Arabische Emirate"),
    "ER" => array("en" => "Eritrea", "it" => "Eritrea", "de" => "Eritrea"),
    "EE" => array("en" => "Estonia", "it" => "Estonia", "de" => "Estland"),
    "ET" => array("en" => "Ethiopia", "it" => "Etiopia", "de" => "Äthiopien"),
    "RU" => array("en" => "Russian Federation", "it" => "Federazione Russa", "de" => "Russische Föderation"),
    "FJ" => array("en" => "Fiji", "it" => "Figi", "de" => "Fidschi"),
    "PH" => array("en" => "Philippines", "it" => "Filippine", "de" => "Philippinen"),
    "FI" => array("en" => "Finland", "it" => "Finlandia", "de" => "Finnland"),
    "FR" => array("en" => "France", "it" => "Francia", "de" => "Frankreich"),
    "GA" => array("en" => "Gabon", "it" => "Gabon", "de" => "Gabun"),
    "GM" => array("en" => "Gambia", "it" => "Gambia", "de" => "Gambia"),
    "GE" => array("en" => "Georgia", "it" => "Georgia", "de" => "Georgien"),
    "GS" => array("en" => "South Georgia And Sandwich Isl.", "it" => "Georgia del Sud e Isole Sandwich Australi", "de" => "Südgeorgien und die Südlichen Sandwichinseln"),
    "DE" => array("en" => "Germany", "it" => "Germania", "de" => "Deutschland"),
    "GH" => array("en" => "Ghana", "it" => "Ghana", "de" => "Ghana"),
    "JM" => array("en" => "Jamaica", "it" => "Giamaica", "de" => "Jamaika"),
    "JP" => array("en" => "Japan", "it" => "Giappone", "de" => "Japan"),
    "GI" => array("en" => "Gibraltar", "it" => "Gibilterra", "de" => "Gibraltar"),
    "DJ" => array("en" => "Djibouti", "it" => "Gibuti", "de" => "Dschibuti"),
    "JO" => array("en" => "Jordan", "it" => "Giordania", "de" => "Jordanien"),
    "GR" => array("en" => "Greece", "it" => "Grecia", "de" => "Griechenland"),
    "GD" => array("en" => "Grenada", "it" => "Grenada", "de" => "Grenada"),
    "GL" => array("en" => "Greenland", "it" => "Groenlandia", "de" => "Grönland"),
    "GP" => array("en" => "Guadeloupe", "it" => "Guadalupa", "de" => "Guadeloupe"),
    "GU" => array("en" => "Guam", "it" => "Guam", "de" => "Guam"),
    "GT" => array("en" => "Guatemala", "it" => "Guatemala", "de" => "Guatemala"),
    "GG" => array("en" => "Guernsey", "it" => "Guernsey", "de" => "Guernsey"),
    "GN" => array("en" => "Guinea", "it" => "Guinea", "de" => "Guinea"),
    "GQ" => array("en" => "Equatorial Guinea", "it" => "Guinea Equatoriale", "de" => "Äquatorialguinea"),
    "GW" => array("en" => "Guinea-Bissau", "it" => "Guinea-Bissau", "de" => "Guinea-Bissau"),
    "GY" => array("en" => "Guyana", "it" => "Guyana", "de" => "Guyana"),
    "GF" => array("en" => "French Guiana", "it" => "Guyana Francese", "de" => "Französisch-Guayana"),
    "HT" => array("en" => "Haiti", "it" => "Haiti", "de" => "Haiti"),
    "HN" => array("en" => "Honduras", "it" => "Honduras", "de" => "Honduras"),
    "HK" => array("en" => "Hong Kong", "it" => "Hong Kong", "de" => "Hongkong"),
    "IN" => array("en" => "India", "it" => "India", "de" => "Indien"),
    "ID" => array("en" => "Indonesia", "it" => "Indonesia", "de" => "Indonesien"),
    "IR" => array("en" => "Iran, Islamic Republic Of", "it" => "Iran", "de" => "Iran"),
    "IQ" => array("en" => "Iraq", "it" => "Iraq", "de" => "Irak"),
    "IE" => array("en" => "Ireland", "it" => "Irlanda", "de" => "Irland"),
    "IS" => array("en" => "Iceland", "it" => "Islanda", "de" => "Island"),
    "BV" => array("en" => "Bouvet Island", "it" => "Isola Bouvet", "de" => "Bouvetinsel"),
    "IM" => array("en" => "Isle Of Man", "it" => "Isola di Man", "de" => "Isle of Man"),
    "CX" => array("en" => "Christmas Island", "it" => "Isola di Natale", "de" => "Weihnachtsinsel"),
    "NF" => array("en" => "Norfolk Island", "it" => "Isola Norfolk", "de" => "Norfolkinsel"),
    "AX" => array("en" => "Aland Islands", "it" => "Isole Åland", "de" => "Åland-Inseln"),
    "KY" => array("en" => "Cayman Islands", "it" => "Isole Cayman", "de" => "Kaimaninseln"),
    "CC" => array("en" => "Cocos (Keeling) Islands", "it" => "Isole Cocos (Keeling)", "de" => "Kokosinseln"),
    "CK" => array("en" => "Cook Islands", "it" => "Isole Cook", "de" => "Cookinseln"),
    "FK" => array("en" => "Falkland Islands (Malvinas)", "it" => "Isole Falkland (Malvine)", "de" => "Falklandinseln"),
    "FO" => array("en" => "Faroe Islands", "it" => "Isole Faroe", "de" => "Färöer-Inseln"),
    "HM" => array("en" => "Heard Island & Mcdonald Islands", "it" => "Isole Heard e McDonald", "de" => "Heard und McDonaldinseln"),
    "MP" => array("en" => "Northern Mariana Islands", "it" => "Isole Marianne Settentrionali", "de" => "Nördliche Marianen"),
    "MH" => array("en" => "Marshall Islands", "it" => "Isole Marshall", "de" => "Marshallinseln"),
    "UM" => array("en" => "United States Outlying Islands", "it" => "Isole Minori Esterne degli Stati Uniti", "de" => "United States Minor Outlying Islands"),
    "SB" => array("en" => "Solomon Islands", "it" => "Isole Salomone", "de" => "Salomonen"),
    "TC" => array("en" => "Turks And Caicos Islands", "it" => "Isole Turks e Caicos", "de" => "Turks- und Caicosinseln"),
    "VI" => array("en" => "Virgin Islands, U.S.", "it" => "Isole Vergini Americane", "de" => "Amerikanische Jungferninseln"),
    "VG" => array("en" => "Virgin Islands, British", "it" => "Isole Vergini Britanniche", "de" => "Britische Jungferninseln"),
    "IL" => array("en" => "Israel", "it" => "Israele", "de" => "Israel"),
    "IT" => array("en" => "Italy", "it" => "Italia", "de" => "Italien"),
    "JE" => array("en" => "Jersey", "it" => "Jersey", "de" => "Jersey"),
    "KZ" => array("en" => "Kazakhstan", "it" => "Kazakistan", "de" => "Kasachstan"),
    "KE" => array("en" => "Kenya", "it" => "Kenya", "de" => "Kenia"),
    "KG" => array("en" => "Kyrgyzstan", "it" => "Kirghizistan", "de" => "Kirgisistan"),
    "KI" => array("en" => "Kiribati", "it" => "Kiribati", "de" => "Kiribati"),
    "KW" => array("en" => "Kuwait", "it" => "Kuwait", "de" => "Kuwait"),
    "LA" => array("en" => "Lao People's Democratic Republic", "it" => "Laos", "de" => "Laos"),
    "LS" => array("en" => "Lesotho", "it" => "Lesotho", "de" => "Lesotho"),
    "LV" => array("en" => "Latvia", "it" => "Lettonia", "de" => "Lettland"),
    "LB" => array("en" => "Lebanon", "it" => "Libano", "de" => "Libanon"),
    "LR" => array("en" => "Liberia", "it" => "Liberia", "de" => "Liberia"),
    "LY" => array("en" => "Libyan Arab Jamahiriya", "it" => "Libia", "de" => "Libyen"),
    "LI" => array("en" => "Liechtenstein", "it" => "Liechtenstein", "de" => "Liechtenstein"),
    "LT" => array("en" => "Lithuania", "it" => "Lituania", "de" => "Litauen"),
    "LU" => array("en" => "Luxembourg", "it" => "Lussemburgo", "de" => "Luxemburg"),
    "MO" => array("en" => "Macao", "it" => "Macao", "de" => "Macau"),
    "MK" => array("en" => "Macedonia", "it" => "Macedonia del Nord", "de" => "Nordmazedonien"),
    "MG" => array("en" => "Madagascar", "it" => "Madagascar", "de" => "Madagaskar"),
    "MW" => array("en" => "Malawi", "it" => "Malawi", "de" => "Malawi"),
    "MV" => array("en" => "Maldives", "it" => "Maldive", "de" => "Malediven"),
    "MY" => array("en" => "Malaysia", "it" => "Malesia", "de" => "Malaysia"),
    "ML" => array("en" => "Mali", "it" => "Mali", "de" => "Mali"),
    "MT" => array("en" => "Malta", "it" => "Malta", "de" => "Malta"),
    "MA" => array("en" => "Morocco", "it" => "Marocco", "de" => "Marokko"),
    "MQ" => array("en" => "Martinique", "it" => "Martinica", "de" => "Martinique"),
    "MR" => array("en" => "Mauritania", "it" => "Mauritania", "de" => "Mauretanien"),
    "MU" => array("en" => "Mauritius", "it" => "Mauritius", "de" => "Mauritius"),
    "YT" => array("en" => "Mayotte", "it" => "Mayotte", "de" => "Mayotte"),
    "MX" => array("en" => "Mexico", "it" => "Messico", "de" => "Mexiko"),
    "FM" => array("en" => "Micronesia, Federated States Of", "it" => "Micronesia", "de" => "Mikronesien"),
    "MD" => array("en" => "Moldova", "it" => "Moldavia", "de" => "Moldawien"),
    "MC" => array("en" => "Monaco", "it" => "Monaco", "de" => "Monaco"),
    "MN" => array("en" => "Mongolia", "it" => "Mongolia", "de" => "Mongolei"),
    "ME" => array("en" => "Montenegro", "it" => "Montenegro", "de" => "Montenegro"),
    "MS" => array("en" => "Montserrat", "it" => "Montserrat", "de" => "Montserrat"),
    "MZ" => array("en" => "Mozambique", "it" => "Mozambico", "de" => "Mosambik"),
    "MM" => array("en" => "Myanmar", "it" => "Myanmar (Birmania)", "de" => "Myanmar"),
    "NA" => array("en" => "Namibia", "it" => "Namibia", "de" => "Namibia"),
    "NR" => array("en" => "Nauru", "it" => "Nauru", "de" => "Nauru"),
    "NP" => array("en" => "Nepal", "it" => "Nepal", "de" => "Nepal"),
    "NI" => array("en" => "Nicaragua", "it" => "Nicaragua", "de" => "Nicaragua"),
    "NE" => array("en" => "Niger", "it" => "Niger", "de" => "Niger"),
    "NG" => array("en" => "Nigeria", "it" => "Nigeria", "de" => "Nigeria"),
    "NU" => array("en" => "Niue", "it" => "Niue", "de" => "Niue"),
    "NO" => array("en" => "Norway", "it" => "Norvegia", "de" => "Norwegen"),
    "NC" => array("en" => "New Caledonia", "it" => "Nuova Caledonia", "de" => "Neukaledonien"),
    "NZ" => array("en" => "New Zealand", "it" => "Nuova Zelanda", "de" => "Neuseeland"),
    "OM" => array("en" => "Oman", "it" => "Oman", "de" => "Oman"),
    "NL" => array("en" => "Netherlands", "it" => "Paesi Bassi", "de" => "Niederlande"),
    "PK" => array("en" => "Pakistan", "it" => "Pakistan", "de" => "Pakistan"),
    "PW" => array("en" => "Palau", "it" => "Palau", "de" => "Palau"),
    "PA" => array("en" => "Panama", "it" => "Panama", "de" => "Panama"),
    "PG" => array("en" => "Papua New Guinea", "it" => "Papua Nuova Guinea", "de" => "Papua-Neuguinea"),
    "PY" => array("en" => "Paraguay", "it" => "Paraguay", "de" => "Paraguay"),
    "PE" => array("en" => "Peru", "it" => "Perù", "de" => "Peru"),
    "PN" => array("en" => "Pitcairn", "it" => "Pitcairn", "de" => "Pitcairninseln"),
    "PF" => array("en" => "French Polynesia", "it" => "Polinesia Francese", "de" => "Französisch-Polynesien"),
    "PL" => array("en" => "Poland", "it" => "Polonia", "de" => "Polen"),
    "PR" => array("en" => "Puerto Rico", "it" => "Porto Rico", "de" => "Puerto Rico"),
    "PT" => array("en" => "Portugal", "it" => "Portogallo", "de" => "Portugal"),
    "QA" => array("en" => "Qatar", "it" => "Qatar", "de" => "Katar"),
    "GB" => array("en" => "United Kingdom", "it" => "Regno Unito", "de" => "Vereinigtes Königreich"),
    "CZ" => array("en" => "Czech Republic", "it" => "Repubblica Ceca", "de" => "Tschechische Republik"),
    "CF" => array("en" => "Central African Republic", "it" => "Repubblica Centrafricana", "de" => "Zentralafrikanische Republik"),
    "CD" => array("en" => "Congo, Democratic Republic", "it" => "Repubblica Democratica del Congo", "de" => "Demokratische Republik Kongo"),
    "DO" => array("en" => "Dominican Republic", "it" => "Repubblica Dominicana", "de" => "Dominikanische Republik"),
    "RE" => array("en" => "Reunion", "it" => "Riunione", "de" => "Réunion"),
    "RO" => array("en" => "Romania", "it" => "Romania", "de" => "Rumänien"),
    "RW" => array("en" => "Rwanda", "it" => "Ruanda", "de" => "Ruanda"),
    "EH" => array("en" => "Western Sahara", "it" => "Sahara Occidentale", "de" => "Westsahara"),
    "KN" => array("en" => "Saint Kitts And Nevis", "it" => "Saint Kitts e Nevis", "de" => "St. Kitts und Nevis"),
    "PM" => array("en" => "Saint Pierre And Miquelon", "it" => "Saint Pierre e Miquelon", "de" => "St. Pierre und Miquelon"),
    "VC" => array("en" => "Saint Vincent And Grenadines", "it" => "Saint Vincent e Grenadine", "de" => "St. Vincent und die Grenadinen"),
    "BL" => array("en" => "Saint Barthelemy", "it" => "Saint-Barthélemy", "de" => "Saint-Barthélemy"),
    "MF" => array("en" => "Saint Martin", "it" => "Saint-Martin", "de" => "Saint-Martin"),
    "WS" => array("en" => "Samoa", "it" => "Samoa", "de" => "Samoa"),
    "AS" => array("en" => "American Samoa", "it" => "Samoa Americane", "de" => "Amerikanisch-Samoa"),
    "SM" => array("en" => "San Marino", "it" => "San Marino", "de" => "San Marino"),
    "SH" => array("en" => "Saint Helena", "it" => "Sant'Elena", "de" => "St. Helena"),
    "LC" => array("en" => "Saint Lucia", "it" => "Santa Lucia", "de" => "St. Lucia"),
    "VA" => array("en" => "Holy See (Vatican City State)", "it" => "Santa Sede (Città del Vaticano)", "de" => "Vatikanstadt"),
    "ST" => array("en" => "Sao Tome And Principe", "it" => "São Tomé e Príncipe", "de" => "São Tomé und Príncipe"),
    "SN" => array("en" => "Senegal", "it" => "Senegal", "de" => "Senegal"),
    "RS" => array("en" => "Serbia", "it" => "Serbia", "de" => "Serbien"),
    "SC" => array("en" => "Seychelles", "it" => "Seychelles", "de" => "Seychellen"),
    "SL" => array("en" => "Sierra Leone", "it" => "Sierra Leone", "de" => "Sierra Leone"),
    "SG" => array("en" => "Singapore", "it" => "Singapore", "de" => "Singapur"),
    "SY" => array("en" => "Syrian Arab Republic", "it" => "Siria", "de" => "Syrien"),
    "SK" => array("en" => "Slovakia", "it" => "Slovacchia", "de" => "Slowakei"),
    "SI" => array("en" => "Slovenia", "it" => "Slovenia", "de" => "Slowenien"),
    "SO" => array("en" => "Somalia", "it" => "Somalia", "de" => "Somalia"),
    "ES" => array("en" => "Spain", "it" => "Spagna", "de" => "Spanien"),
    "LK" => array("en" => "Sri Lanka", "it" => "Sri Lanka", "de" => "Sri Lanka"),
    "US" => array("en" => "United States", "it" => "Stati Uniti", "de" => "Vereinigte Staaten"),
    "ZA" => array("en" => "South Africa", "it" => "Sudafrica", "de" => "Südafrika"),
    "SD" => array("en" => "Sudan", "it" => "Sudan", "de" => "Sudan"),
    "SR" => array("en" => "Suriname", "it" => "Suriname", "de" => "Suriname"),
    "SJ" => array("en" => "Svalbard And Jan Mayen", "it" => "Svalbard e Jan Mayen", "de" => "Spitzbergen und Jan Mayen"),
    "SE" => array("en" => "Sweden", "it" => "Svezia", "de" => "Schweden"),
    "CH" => array("en" => "Switzerland", "it" => "Svizzera", "de" => "Schweiz"),
    "SZ" => array("en" => "Swaziland", "it" => "Swaziland", "de" => "Eswatini"),
    "TJ" => array("en" => "Tajikistan", "it" => "Tagikistan", "de" => "Tadschikistan"),
    "TW" => array("en" => "Taiwan", "it" => "Taiwan", "de" => "Taiwan"),
    "TZ" => array("en" => "Tanzania", "it" => "Tanzania", "de" => "Tansania"),
    "TF" => array("en" => "French Southern Territories", "it" => "Territori Francesi del Sud", "de" => "Französische Süd- und Antarktisgebiete"),
    "PS" => array("en" => "Palestinian Territory, Occupied", "it" => "Territori Palestinesi", "de" => "Palästinensische Autonomiegebiete"),
    "IO" => array("en" => "British Indian Ocean Territory", "it" => "Territorio Britannico dell'Oceano Indiano", "de" => "Britisches Territorium im Indischen Ozean"),
    "TH" => array("en" => "Thailand", "it" => "Thailandia", "de" => "Thailand"),
    "TL" => array("en" => "Timor-Leste", "it" => "Timor Est", "de" => "Osttimor"),
    "TG" => array("en" => "Togo", "it" => "Togo", "de" => "Togo"),
    "TK" => array("en" => "Tokelau", "it" => "Tokelau", "de" => "Tokelau"),
    "TO" => array("en" => "Tonga", "it" => "Tonga", "de" => "Tonga"),
    "TT" => array("en" => "Trinidad And Tobago", "it" => "Trinidad e Tobago", "de" => "Trinidad und Tobago"),
    "TN" => array("en" => "Tunisia", "it" => "Tunisia", "de" => "Tunesien"),
    "TR" => array("en" => "Turkey", "it" => "Turchia", "de" => "Türkei"),
    "TM" => array("en" => "Turkmenistan", "it" => "Turkmenistan", "de" => "Turkmenistan"),
    "TV" => array("en" => "Tuvalu", "it" => "Tuvalu", "de" => "Tuvalu"),
    "UA" => array("en" => "Ukraine", "it" => "Ucraina", "de" => "Ukraine"),
    "UG" => array("en" => "Uganda", "it" => "Uganda", "de" => "Uganda"),
    "HU" => array("en" => "Hungary", "it" => "Ungheria", "de" => "Ungarn"),
    "UY" => array("en" => "Uruguay", "it" => "Uruguay", "de" => "Uruguay"),
    "UZ" => array("en" => "Uzbekistan", "it" => "Uzbekistan", "de" => "Usbekistan"),
    "VU" => array("en" => "Vanuatu", "it" => "Vanuatu", "de" => "Vanuatu"),
    "VE" => array("en" => "Venezuela", "it" => "Venezuela", "de" => "Venezuela"),
    "VN" => array("en" => "Viet Nam", "it" => "Vietnam", "de" => "Vietnam"),
    "WF" => array("en" => "Wallis And Futuna", "it" => "Wallis e Futuna", "de" => "Wallis und Futuna"),
    "YE" => array("en" => "Yemen", "it" => "Yemen", "de" => "Jemen"),
    "ZM" => array("en" => "Zambia", "it" => "Zambia", "de" => "Sambia"),
    ];


    public static function iso2name(string $iso, $lang = "it"): string
    {
        if (array_key_exists($iso, self::$countries))
            return self::$countries[$iso][$lang];
        else
            throw new Error("Country with ISO Code $iso does not exist.");
    }

    public static function options(string $selected = '', $lang = "it"): void
    {
        foreach (self::$countries as $key => $val) {
            $label = $val[$lang];
            $sel = $selected == $key ? "selected" : "";
            echo "<option value='$key' $sel>$label</option>";
        }
    }
}